// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY-TD17seFHtJV5zlFZ3c1vugqLGdkma8',
    appId: '1:1018576401228:web:a5a9bffba4fabc538c15e9',
    messagingSenderId: '1018576401228',
    projectId: 'vinnovate-83a4e',
    authDomain: 'vinnovate-83a4e.firebaseapp.com',
    storageBucket: 'vinnovate-83a4e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjFlfaUzHfOpwCFp7V8bfZRG8OSEFmcdI',
    appId: '1:1018576401228:android:67e9417f0bc6def48c15e9',
    messagingSenderId: '1018576401228',
    projectId: 'vinnovate-83a4e',
    storageBucket: 'vinnovate-83a4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARrz8Om2qgwjC0_RfWblrBq-9Bgwl3D18',
    appId: '1:1018576401228:ios:1731395d5eacbca58c15e9',
    messagingSenderId: '1018576401228',
    projectId: 'vinnovate-83a4e',
    storageBucket: 'vinnovate-83a4e.appspot.com',
    iosClientId: '1018576401228-cj4bbiji3e58qbu1nljh27ibnorfct2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.vinnovateTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARrz8Om2qgwjC0_RfWblrBq-9Bgwl3D18',
    appId: '1:1018576401228:ios:1731395d5eacbca58c15e9',
    messagingSenderId: '1018576401228',
    projectId: 'vinnovate-83a4e',
    storageBucket: 'vinnovate-83a4e.appspot.com',
    iosClientId: '1018576401228-cj4bbiji3e58qbu1nljh27ibnorfct2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.vinnovateTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY-TD17seFHtJV5zlFZ3c1vugqLGdkma8',
    appId: '1:1018576401228:web:a7517456c6123ff58c15e9',
    messagingSenderId: '1018576401228',
    projectId: 'vinnovate-83a4e',
    authDomain: 'vinnovate-83a4e.firebaseapp.com',
    storageBucket: 'vinnovate-83a4e.appspot.com',
  );
}
